# The class vocabulary shared by the CSS, page, and JS prompts. Because each file is
# generated by an independent LLM call, this contract is what keeps them coherent —
# every prompt embeds it verbatim.
CLASS_CONTRACT = """SHARED CLASS CONTRACT — these exact class names bind HTML, CSS and JS together:
- Navbar: <header class="navbar"> > <nav class="nav-inner container"> containing
  <a class="logo" href="index.html">, <button class="hamburger" aria-label="Menu">☰</button>,
  <ul class="nav-links"> with one <li><a href="page.html"> per page.
  The link for the CURRENT page carries class="active". Scrolled state adds .scrolled to .navbar (JS).
- Layout: .container (max-width 1140px, centered, side padding).
- Hero: <section class="hero" id="hero"> > .hero-content with h1, p, and an <a class="btn btn-primary">.
- Sections: <section class="section section-KIND" id="ID"> where KIND is the section kind
  (services, about, team, testimonials, pricing, faq, contact, cta, menu, features, gallery,
  hours, location...). Each starts with <div class="section-head"> holding <h2> and optional <p class="section-lead">.
- Cards: <div class="cards"> holding <div class="card"> items; icon in <div class="card-icon">, then <h3>, <p>.
- Imagery (a photo): <figure class="media"><img class="media-img" src="https://picsum.photos/seed/SEED/W/H" width="W" height="H" alt="SUBJECT" loading="lazy"></figure>.
  SEED is the photo SUBJECT slugified (lowercase, every run of non-alphanumerics → a single hyphen, trimmed). The .media wrapper carries a brand gradient so nothing flashes white while the photo loads or if it fails.
- Hero WITH a photo: <section class="hero has-photo" id="hero"> whose FIRST child is <img class="hero-bg" src="..." width="1600" height="900" alt="SUBJECT">, then <div class="hero-overlay"></div>, then the .container > .hero-content. The overlay is a brand-color gradient that keeps white hero text readable over any photo.
- Media-with-text row: <div class="media-row"> holding a <figure class="media"> and a text column (.media-text) side by side — for about/story sections.
- Gallery: inside <section class="section section-gallery">, a <div class="gallery"> of <figure class="media gallery-item"> photos, each with an optional <figcaption>.
- Stats (count-up): <div class="stats"> of <div class="stat"><span class="stat-value" data-target="1200">0</span><span class="stat-label">…</span></div>. JS counts each stat-value from 0 up to data-target when it scrolls in.
- Buttons: .btn base, .btn-primary filled, .btn-outline outlined.
- Forms: <form class="contact-form"> with <div class="form-group"> per field
  (label + input/textarea), <button type="submit" class="btn btn-primary">, and IMMEDIATELY after
  the button: <p class="form-success" style="display:none;"></p>.
- Reveal animations: an element opts into a scroll reveal with ONE of .fade-in, .slide-up, .slide-left, .slide-right, or .zoom-in. All start hidden/offset and play when JS adds .visible.
- Footer: <footer class="footer"> > .footer-inner.container with brand column, quick-links column
  (real page links), and <p class="copyright">."""


CSS_PROMPT = """You are an expert senior front-end developer writing the single shared stylesheet (style.css) for a multi-page website. You receive a design spec (JSON), the list of section kinds used across the site, and the page manifest.

OUTPUT FORMAT — CRITICAL:
Output ONLY raw CSS. No explanations, no markdown fences, no commentary. First character is the first character of the CSS.

""" + CLASS_CONTRACT + """

CSS REQUIREMENTS:
- CSS custom properties in :root for ALL palette colors — use the design spec hex values VERBATIM (--primary, --primary-dark, --accent, --bg, --surface, --text, --muted) plus --radius from the spec.
- TYPE & SPACING SCALE — put these in :root and use them consistently instead of inventing sizes per element (this is what makes the site feel designed, not assembled):
  --h1: clamp(2.5rem, 5vw, 4rem); --h2: clamp(1.9rem, 3vw, 2.5rem); --h3: 1.25rem; --lead: 1.15rem; --body: 1rem;
  Body line-height 1.6, heading line-height 1.15. Section vertical padding 5rem 0 (3.5rem on mobile). .container side padding 1.5rem. Card gap 1.5rem. Consistent element spacing from an 8px rhythm (0.5/1/1.5/2/3rem). h1 uses --h1, section h2 uses --h2, card h3 uses --h3, .section-lead uses --lead.
- Font families from the design spec (the pages load the Google Fonts URL): headings use heading_font, body uses body_font.
- Mobile-first responsive design with media queries at 768px and 1024px+.
- html { scroll-behavior: smooth; }
- body { padding-top: 70px; } to clear the fixed navbar.
- Navbar: position: fixed (NOT sticky), top: 0; left: 0; width: 100%; z-index: 1000; height 70px.
  Default (before scrolling) background MUST be a dark semi-transparent color such as rgba(0,0,0,0.35) — NEVER white, never light. Logo and nav link text are white (#fff) so they are always readable.
  .navbar.scrolled switches to solid var(--primary-dark) with a subtle box-shadow. Text stays white.
  CRITICAL: never set any navbar state to white, light gray, or any light color — white text on a light background is invisible.
  .nav-links a.active gets a visible current-page indicator (underline or accent color).
- Mobile menu — EXACT pattern, no variations:
  Base (outside media queries): .hamburger { display: none; background: none; border: none; color: #fff; font-size: 1.6rem; cursor: pointer; } and .nav-links { display: flex; }
  At max-width 767px: .hamburger { display: block; } and .nav-links { display: none; flex-direction: column; position: absolute; top: 100%; left: 0; width: 100%; background: var(--primary-dark); padding: 1.5rem 2rem; z-index: 999; } and .nav-links.active { display: flex; }
  NEVER use transform/opacity/visibility to toggle the mobile menu — always display:none / display:flex.
- Hero: visually striking, large (min-height around 85vh on the home hero), background per the spec's hero_treatment — always a gradient or gradient + overlay, never one flat color. Hero text and CTA visible instantly (no JS reveal classes on the hero).
  · If the page's hero uses a photo (.hero.has-photo with an <img class="hero-bg">): position the hero relative; the .hero-bg is position:absolute, inset:0, width/height:100%, object-fit:cover, z-index:0; .hero-overlay is absolute, inset:0, z-index:1, a brand gradient with alpha (e.g. linear-gradient(135deg, rgba(primary,0.85), rgba(primary_dark,0.9))) so white text stays readable; .hero-content is position:relative, z-index:2.
  · A gentle HERO ENTRANCE is welcome and safe: animate .hero-content (or its h1/p/CTA) in on page load via a CSS @keyframes that ENDS fully visible (e.g. heroRise: from opacity 0 translateY(20px) to opacity 1) — never opacity:0 that depends on JS. Stagger the h1, p and CTA by small animation-delays.
- IMAGERY CSS (photos are core now):
  · .media: position relative; overflow hidden; border-radius var(--radius); background: a brand gradient (linear-gradient from primary to primary_dark) so it shows a branded block before the photo loads or if it 404s — never white.
  · .media-img (and .hero-bg): display block; width:100%; height:100%; object-fit:cover. Give .media a sensible aspect-ratio (e.g. 4/3 for cards, 16/9 for wide) so images reserve space and don't shift layout.
  · Subtle photo polish: on hover, .media img scales to ~1.05 with a 0.5s ease (overflow hidden crops it); optionally a faint brand-tinted gradient overlay via .media::after for cohesion.
  · .media-row: two-column grid on desktop (image + .media-text), single column stacked on mobile, with comfortable gap.
  · .gallery: responsive grid (repeat(auto-fit, minmax(220px, 1fr))) of .gallery-item figures with a small gap; figcaptions are small, muted.
  · .media--gradient (used when photos are disabled): a rich multi-stop brand gradient plus a faint diagonal pattern, filling the same box — so the layout still looks intentional with no <img>.
- COLOR RICHNESS — do not paint flat:
  · .btn-primary uses a gradient (e.g. linear-gradient(135deg, var(--accent), a slightly deeper shade)) and a soft colored shadow tinted toward the brand, not flat grey; hover deepens both.
  · Give ONE key heading per page gradient text (background: linear-gradient(...); -webkit-background-clip:text; background-clip:text; color:transparent) — e.g. section h2s or the hero h1, per css_notes.
  · Card and media shadows are tinted toward primary_dark (e.g. rgba of primary_dark), not neutral grey, for depth.
  · The bold brand section from the rhythm uses a primary→primary_dark gradient (optionally slowly animated, see below), not a flat solid.
- Reveal animation classes — define ALL of these; each starts hidden and .visible brings it to rest (opacity:1; transform:none) over ~0.6s ease:
  · .fade-in { opacity:0 }  · .slide-up { opacity:0; translateY(28px) }  · .slide-left { opacity:0; translateX(-32px) }  · .slide-right { opacity:0; translateX(32px) }  · .zoom-in { opacity:0; scale .92 (transform: scale(.92)) }.
  Style ONLY the classes — placement lives in the HTML.
- Staggered cascade: within .cards, give .card:nth-child(2)/(3)/(4) transition-delay 0.1s/0.2s/0.3s so visible cards cascade in.
- One tasteful ambient motion: EITHER a slow animated gradient on the hero/bold section (@keyframes drifting background-position over ~12s) OR a soft floating accent blob (@keyframes float translating a few px) behind a heading. Keep it subtle; put it behind a prefers-reduced-motion guard.
- Stats: .stats is a flex/grid row; .stat-value is large and bold (uses --h2 scale or larger, heading font); .stat-label is muted and small.
- Hover effects on ALL interactive elements with 0.3s ease transitions: .btn scales slightly (transform: scale(1.04)) and deepens its shadow, .card lifts (translateY(-6px) + deeper tinted shadow), nav links get a color/underline shift, .media images zoom.
- Section backgrounds follow the spec's section_rhythm literally — apply each entry as written: "bg" → var(--bg); "surface" → var(--surface); "primary tint 10% over bg" → the primary color at ~10% opacity over bg (use color-mix or an rgba of the primary); "primary solid with white text" / "primary_dark solid with white text" → that solid color with white headings, white body, and lightened muted text. Write explicit backgrounds for each .section-KIND used on the site so the rhythm alternates; never leave more than 2 consecutive plain-bg sections.
- Decorative details from the spec's css_notes — implement them concretely (accent border-left on cards, gradient text on key h2s via background-clip, soft ::before blobs, etc.).
- Cards: subtle shadows, var(--radius) corners.
- .section padding: generous vertical rhythm (e.g. 5rem 0), .section-head centered with strong h2 hierarchy.
- Contact form styles: clean inputs with visible focus states using the accent (:focus-visible outline — never remove focus outlines without replacing them); .form-success styled as a success notice (it is display:none until JS reveals it).
- Footer: dark (var(--primary-dark)) with light text, brand column + quick links + copyright.
- Respect prefers-reduced-motion: wrap a media query that disables the entrance animations and transitions for users who ask for less motion.
- Strong visual hierarchy via font sizes, weights and spacing throughout. The result must look like a premium professional studio built it — decisive spacing rhythm, aligned edges, no orphan elements.

BEFORE YOU FINISH — verify each of these is true in your CSS, fix any that aren't:
□ :root has every palette variable with the spec's exact hex values, plus the type & spacing scale.
□ Default navbar background is dark/translucent (never white/light); .scrolled is solid var(--primary-dark); all navbar text is white.
□ Mobile menu uses the exact display:none / display:flex pattern (no transform/opacity/visibility toggling).
□ ALL reveal classes are defined with .visible: .fade-in, .slide-up, .slide-left, .slide-right, .zoom-in. The hero relies on NO JS reveal class (a CSS load-entrance that ends fully visible is fine).
□ .media (gradient placeholder bg, overflow hidden, radius, aspect-ratio), .media-img/.hero-bg (object-fit:cover), .hero-overlay, .media-row, .gallery, .media--gradient, .stats/.stat-value/.stat-label are all styled.
□ Color is layered, not flat: gradient .btn-primary with a tinted shadow, one gradient-text heading, brand-tinted shadows, a gradient (not solid) bold section.
□ Every .section-KIND used on the site has an explicit background following the rhythm; at least one bold brand section exists; no 3+ consecutive plain-bg sections.
□ Buttons, cards, links and images all have hover states; one subtle ambient motion exists; a prefers-reduced-motion block disables entrance animations, ambient motion AND the count-up hover transitions."""


PAGE_PROMPT = """You are an expert senior front-end developer generating ONE complete HTML page of a multi-page website. You receive: the site brief, the copy for THIS page (JSON — headings, text, cards), the design spec, the site navigation manifest, and the shared stylesheet.

OUTPUT FORMAT — CRITICAL:
Output ONLY the raw, complete HTML document for this one page. No explanations, no markdown fences, no commentary. First characters are "<!DOCTYPE html>".

""" + CLASS_CONTRACT + """

HTML REQUIREMENTS:
- Complete valid HTML5 document: doctype, <html lang="en">, <head> with charset, viewport meta, <title> and <meta name="description"> from the page copy.
- In <head>: the Google Fonts <link> from the design spec, then <link rel="stylesheet" href="style.css">.
- <script src="script.js"></script> immediately before </body>.
- Navbar exactly per the contract, with links to every page in the manifest using their exact filenames. The link to THIS page gets class="active". Same navbar markup on every page.
- Render every section from the page copy JSON, in order, as <section class="section section-KIND" id="ID"> (the hero uses <section class="hero" id="hero">). Use the copy EXACTLY as written — every heading, subheading, body text, card title, card body, CTA label verbatim. THE COPY IS LAW: do not rewrite, shorten, or "improve" it. You may only add small structural text like form field labels.
- Cards from "items" arrays follow the card contract (icon, h3, p). Testimonial cards wrap the body in quotation marks with attribution below. FAQ items render title as the question (h3) and body as the answer.
- IMAGERY — render photos wherever the copy provides an "image" subject (per the contract's imagery markup). Honor the design spec's "imagery" direction for mood/placement:
  · A section (or card/item) with an "image" value gets a photo. The home hero should be a photo hero (.hero.has-photo) when its copy has an "image"; use the design spec's imagery/hero_treatment to decide the overlay.
  · An about/story section with an "image" uses the .media-row (photo beside the text).
  · A "gallery" section renders each item's "image" as a .gallery-item figure (item "title" → <figcaption>). A "team" section renders each member with their photo, name and role. A "stats" section renders .stat blocks with data-target from each item's "value" and the "label" text (default the visible number text to 0).
  · Small feature/service card grids stay ICON-led (emoji), not thumbnails, unless the copy explicitly gives those cards an "image".
  · Build every image URL as https://picsum.photos/seed/SEED/W/H where SEED is the "image" subject slugified (lowercase; each run of non-alphanumeric chars → one hyphen; trim hyphens). Pick W/H to match the slot (hero 1600x900, media-row ~800x600, gallery/card ~600x450). Put the subject text verbatim in alt. Give EVERY <img> width, height and a loading attribute: the above-the-fold hero-bg uses loading="eager"; every other image uses loading="lazy".
- IMAGE MODE (stated in the input): if "photos" → use the picsum <img> markup above. If "svg-only" → do NOT emit any external <img>; instead render the SAME wrappers with a brand-gradient fill: use <figure class="media media--gradient" role="img" aria-label="SUBJECT"></figure> for photos, and a plain gradient hero <section class="hero" id="hero"> (no hero-bg img, no external URL anywhere). Everything else is identical.
- If this page has a "contact" section, include a contact form per the contract: name, email, message fields (plus fields that fit the business, e.g. date/guests for reservations), submit button, and the hidden <p class="form-success"> right after the button.
- Semantic HTML: <header>, <nav>, <main>, <section>, <footer>, <article> where appropriate.
- Accessibility is part of correctness: every form input has a <label for=...>; every image has meaningful alt text; the hamburger button keeps its aria-label; heading levels never skip (h1 → h2 → h3); link text says where it goes.
- Footer per the contract with the site's footer tagline, quick links to all pages (exact filenames), and the copyright line.
- ANIMATION PLACEMENT RULES: never put a reveal class (.fade-in/.slide-up/.slide-left/.slide-right/.zoom-in) on any <section> element — only on child elements INSIDE sections (individual cards, headings, media, content blocks). NEVER put reveal classes on the hero section or ANY of its children — the hero must be fully visible instantly (its entrance is CSS-driven). Vary the directions tastefully: e.g. a section heading .fade-in, a media figure .slide-left with its text .slide-right, cards .slide-up or .zoom-in — don't make the whole page one identical motion.
- CTA hrefs: if the copy's cta href points to a page, use the exact filename; same-page targets use #section-id.
- FORBIDDEN: alert(), localStorage, sessionStorage, Lorem Ipsum, placeholder text, external JS libraries, inline event handlers (onclick=...), broken links to pages not in the manifest.

BEFORE YOU FINISH — verify each of these, fix any that aren't true:
□ doctype, <html lang>, charset, viewport meta, <title> + meta description, Google Fonts link, style.css link all present; script.js right before </body>.
□ Navbar markup matches the contract; every nav + footer link points to a real manifest filename; THIS page's link has class="active".
□ Every section from the copy is rendered in order with its exact text (copy is law); the hero uses <section class="hero" id="hero"> (add class="has-photo" + hero-bg + hero-overlay when in photos mode with a hero image).
□ Every copy "image" subject became a photo in the right wrapper (media / media-row / gallery / hero-bg); no reveal class on any <section> or on the hero or its children.
□ Photos mode: every <img> uses a picsum seed slugified from its subject, with width, height, loading="lazy" and descriptive alt. SVG-only mode: NO external <img>/URL anywhere — media--gradient wrappers and a plain gradient hero instead.
□ If there's a contact section, the form has all fields with <label>, a submit button, and the hidden .form-success right after it.
□ No alert()/localStorage/sessionStorage, no inline handlers, no external libraries, no placeholder text, every <img> has alt."""


JS_PROMPT = """You are an expert senior front-end developer writing the single shared script (script.js) for a multi-page website. The same file loads on every page, so EVERY element lookup must be null-checked — a page may not contain a given element.

OUTPUT FORMAT — CRITICAL:
Output ONLY raw JavaScript. No explanations, no markdown fences, no commentary. The last character of your output is the closing brace or statement of the code.

""" + CLASS_CONTRACT + """

JAVASCRIPT REQUIREMENTS:
- Vanilla JavaScript only — no libraries, no frameworks, no jQuery.
- Wrap everything so it runs after DOM parse (the script tag is at the end of <body>, so top-level code is fine — but still null-check every query).
- Navbar scroll state: add .scrolled to .navbar when window.scrollY > 50, remove below.
- Mobile menu — EXACT pattern: hamburger click toggles .active on .nav-links and swaps its own textContent between "☰" and "✕". Every link inside .nav-links also gets a click listener that closes the menu (remove .active, reset hamburger text to "☰"). Guard: only wire this if both elements exist.
- IntersectionObserver (reveals): observe every element matching ".fade-in, .slide-up, .slide-left, .slide-right, .zoom-in" with threshold 0.15. When entries intersect, set each element's style.transitionDelay staggered by its index within the batch (0s, 0.1s, 0.2s, 0.3s…) before adding .visible, then unobserve it.
- Count-up stats: for each .stat-value with a data-target, animate its textContent from 0 to the target integer over ~1.5s (requestAnimationFrame, ease-out) the first time it scrolls into view (use an IntersectionObserver, unobserve after firing). Preserve any trailing/leading non-digits in the label if present; keep it simple — parseInt the data-target. Guard: skip if there are none.
- Image fallback (offline-safe): for every <img>, if it fails to load — attach an 'error' listener AND also check img.complete && img.naturalWidth === 0 at startup (covers already-failed/cached) — replace its src ONCE with an inline SVG data-URI: a gradient rectangle using the site's brand colors read from getComputedStyle(document.documentElement) (--primary, --primary-dark), sized to the img's width/height attributes (fallback 1200x800). This makes exported sites degrade to branded placeholders instead of broken-image icons when picsum is unreachable. Set a data-flag first so it never loops.
- Smooth scroll: intercept clicks ONLY on anchors whose href starts with "#" (same-page). Links to other pages (about.html etc.) must navigate normally — do not preventDefault on them. Null-check the target before scrolling.
- Active section highlight: if the page has same-page # links in the nav, highlight the one for the section in view while scrolling. Skip entirely when there are none.
- Contact form: for every form.contact-form — intercept submit, preventDefault, NEVER call alert() (forbidden). Set the sibling .form-success element's textContent to a friendly confirmation, set its style.display to "block", and call form.reset() after a short delay.
- FORBIDDEN: alert(), confirm(), prompt(), localStorage, sessionStorage (the preview sandbox throws on storage access), document.write, external requests (fetch/XHR).

BEFORE YOU FINISH — verify each of these, fix any that aren't true:
□ Every querySelector / getElementById result is null-checked before use (the same file runs on every page).
□ Navbar scroll toggles .scrolled at scrollY > 50; hamburger toggles .active and swaps ☰/✕; nav links close the menu — all guarded by existence checks.
□ IntersectionObserver observes ALL reveal classes (.fade-in/.slide-up/.slide-left/.slide-right/.zoom-in) at threshold 0.15 with staggered transitionDelay, then unobserves.
□ .stat-value[data-target] elements count up from 0 once in view; every <img> gets a one-time brand-gradient SVG fallback on load failure.
□ Smooth-scroll only preventDefaults on href^="#" links; cross-page links navigate normally.
□ Each form.contact-form intercepts submit, reveals its .form-success, resets — never alert().
□ No alert/confirm/prompt, no localStorage/sessionStorage, no fetch/XHR, no external libraries."""
